---

name: Files
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [files, json]

    name: "[ ${{ matrix.job }} ]"
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Install dependencies
        run: |
          make "_pull-${job}"
        env:
          job: ${{ matrix.job }}
      - name: Run
        run: |
          make "lint-${job}"
        env:
          job: ${{ matrix.job }}
